### ISSUE TITLE
Make Header for the Website 🎊

### ISSUE THREAD

**Issue by iamBijoyKar** [TechStarHub/meme-gen#1]
## Description 

Make a fully functional Header for this website. The heading will be `MemeGen` and make sure to use the same color as the theme provided in the `/theme` directory.

**Comment by QuangtinB2015015** [comment]
Hello!

Make Header for the Website 🎊 #1

![image](https://github.com/TechStarHub/meme-gen/assets/141598062/be6b191e-50b9-4dbf-9fc5-14201f4e2a6e)

**Comment by iamBijoyKar** [comment]
Hey @QuangtinB2015015, thanks for the suggestion. If you want to contribute then go for it 👍, I made a basic figma design so follow the design, and I added some brand assets in `src/assets/brand` directory, use those.

***Design Link 👉*** https://www.figma.com/file/2CFGWsSol6c6SwDZ9PaaD1/MemeGen?type=design&node-id=0%3A1&mode=design&t=ln9sdKuNftajEeLs-1

@Arnab0089
