### ISSUE TITLE
Fix the Hamburger Menu Icon 🛠️ 

### ISSUE THREAD

**Issue by iamBijoyKar** [TechStarHub/meme-gen#6]
## Fix the Hamburger Menu 
Follow the figma design and make these changes.

![image](https://github.com/TechStarHub/meme-gen/assets/85790967/ebdf2dfd-aa96-4230-90c6-0d9d4761b237)

## Changes
- Use the right menu icon
- Fix the size of the icon 
- Fix the margin of the icon 
- Fix the color of the icon

**Comment by zablon-oigo** [comment]
I can tackle this ,  please assign me

**Comment by iamBijoyKar** [comment]
Go for it 👍

**Comment by zablon-oigo** [comment]
> Go for it 👍

Do you have a design that you might prefer ? Or I should come up with my own

**Comment by iamBijoyKar** [comment]
Use the provided figma design in Readme

**Comment by zablon-oigo** [comment]
hello Here is my submission, I would like to hear your review before pushing it
![Screen Shot 2023-11-09 at 18 58 26](https://github.com/TechStarHub/meme-gen/assets/143833326/8639202c-e895-482b-9b41-6449ae98388c)

**Comment by zablon-oigo** [comment]
How about now

> 1. Align the menu icon with the brand logo
> 2. Give a little margin in the right of the menu icon
> 
> The rest is good 👌

How about now
![Screen Shot 2023-11-09 at 19 31 16](https://github.com/TechStarHub/meme-gen/assets/143833326/4920fa0e-80c5-4a0c-878a-755ed614537c)

**Comment by iamBijoyKar** [comment]
Much better 👍, make PR
